//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public short BookID { get; set; }
        public string BookTitle { get; set; }
        public string BookType { get; set; }
        public string Rating { get; set; }
        public string Publisher { get; set; }
        public string Author { get; set; }
        public string Media { get; set; }
        public Nullable<short> TotalStock { get; set; }
        public Nullable<short> NumberBorrowed { get; set; }
    }
}
